
package br.gov.camara.sitcamaraws.deputados;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Deputados", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/Deputados", wsdlLocation = "http://www.camara.gov.br/SitCamaraWS/Deputados.asmx?wsdl")
public class Deputados
    extends Service
{

    private final static URL DEPUTADOS_WSDL_LOCATION;
    private final static WebServiceException DEPUTADOS_EXCEPTION;
    private final static QName DEPUTADOS_QNAME = new QName("http://www.camara.gov.br/SitCamaraWS/Deputados", "Deputados");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.camara.gov.br/SitCamaraWS/Deputados.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEPUTADOS_WSDL_LOCATION = url;
        DEPUTADOS_EXCEPTION = e;
    }

    public Deputados() {
        super(__getWsdlLocation(), DEPUTADOS_QNAME);
    }

    public Deputados(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEPUTADOS_QNAME, features);
    }

    public Deputados(URL wsdlLocation) {
        super(wsdlLocation, DEPUTADOS_QNAME);
    }

    public Deputados(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEPUTADOS_QNAME, features);
    }

    public Deputados(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Deputados(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DeputadosSoap
     */
    @WebEndpoint(name = "DeputadosSoap")
    public DeputadosSoap getDeputadosSoap() {
        return super.getPort(new QName("http://www.camara.gov.br/SitCamaraWS/Deputados", "DeputadosSoap"), DeputadosSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeputadosSoap
     */
    @WebEndpoint(name = "DeputadosSoap")
    public DeputadosSoap getDeputadosSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.camara.gov.br/SitCamaraWS/Deputados", "DeputadosSoap"), DeputadosSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEPUTADOS_EXCEPTION!= null) {
            throw DEPUTADOS_EXCEPTION;
        }
        return DEPUTADOS_WSDL_LOCATION;
    }

}
