
package br.gov.camara.sitcamaraws.deputados;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DeputadosSoap", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/Deputados")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DeputadosSoap {


    /**
     * 
     * @return
     *     returns br.gov.camara.sitcamaraws.deputados.ObterDeputadosResponse.ObterDeputadosResult
     */
    @WebMethod(operationName = "ObterDeputados", action = "http://www.camara.gov.br/SitCamaraWS/Deputados/ObterDeputados")
    @WebResult(name = "ObterDeputadosResult", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/Deputados")
    @RequestWrapper(localName = "ObterDeputados", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/Deputados", className = "br.gov.camara.sitcamaraws.deputados.ObterDeputados")
    @ResponseWrapper(localName = "ObterDeputadosResponse", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/Deputados", className = "br.gov.camara.sitcamaraws.deputados.ObterDeputadosResponse")
    public br.gov.camara.sitcamaraws.deputados.ObterDeputadosResponse.ObterDeputadosResult obterDeputados();

    /**
     * 
     * @return
     *     returns br.gov.camara.sitcamaraws.deputados.ObterPartidosCDResponse.ObterPartidosCDResult
     */
    @WebMethod(operationName = "ObterPartidosCD", action = "http://www.camara.gov.br/SitCamaraWS/Deputados/ObterPartidosCD")
    @WebResult(name = "ObterPartidosCDResult", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/Deputados")
    @RequestWrapper(localName = "ObterPartidosCD", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/Deputados", className = "br.gov.camara.sitcamaraws.deputados.ObterPartidosCD")
    @ResponseWrapper(localName = "ObterPartidosCDResponse", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/Deputados", className = "br.gov.camara.sitcamaraws.deputados.ObterPartidosCDResponse")
    public br.gov.camara.sitcamaraws.deputados.ObterPartidosCDResponse.ObterPartidosCDResult obterPartidosCD();

    /**
     * 
     * @param idBloco
     * @param numLegislatura
     * @return
     *     returns br.gov.camara.sitcamaraws.deputados.ObterPartidosBlocoCDResponse.ObterPartidosBlocoCDResult
     */
    @WebMethod(operationName = "ObterPartidosBlocoCD", action = "http://www.camara.gov.br/SitCamaraWS/Deputados/ObterPartidosBlocoCD")
    @WebResult(name = "ObterPartidosBlocoCDResult", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/Deputados")
    @RequestWrapper(localName = "ObterPartidosBlocoCD", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/Deputados", className = "br.gov.camara.sitcamaraws.deputados.ObterPartidosBlocoCD")
    @ResponseWrapper(localName = "ObterPartidosBlocoCDResponse", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/Deputados", className = "br.gov.camara.sitcamaraws.deputados.ObterPartidosBlocoCDResponse")
    public br.gov.camara.sitcamaraws.deputados.ObterPartidosBlocoCDResponse.ObterPartidosBlocoCDResult obterPartidosBlocoCD(
        @WebParam(name = "idBloco", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/Deputados")
        String idBloco,
        @WebParam(name = "numLegislatura", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/Deputados")
        String numLegislatura);

    /**
     * 
     * @param ideCadastro
     * @param numLegislatura
     * @return
     *     returns br.gov.camara.sitcamaraws.deputados.ObterDetalhesDeputadoResponse.ObterDetalhesDeputadoResult
     */
    @WebMethod(operationName = "ObterDetalhesDeputado", action = "http://www.camara.gov.br/SitCamaraWS/Deputados/ObterDetalhesDeputado")
    @WebResult(name = "ObterDetalhesDeputadoResult", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/Deputados")
    @RequestWrapper(localName = "ObterDetalhesDeputado", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/Deputados", className = "br.gov.camara.sitcamaraws.deputados.ObterDetalhesDeputado")
    @ResponseWrapper(localName = "ObterDetalhesDeputadoResponse", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/Deputados", className = "br.gov.camara.sitcamaraws.deputados.ObterDetalhesDeputadoResponse")
    public br.gov.camara.sitcamaraws.deputados.ObterDetalhesDeputadoResponse.ObterDetalhesDeputadoResult obterDetalhesDeputado(
        @WebParam(name = "ideCadastro", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/Deputados")
        String ideCadastro,
        @WebParam(name = "numLegislatura", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/Deputados")
        String numLegislatura);

    /**
     * 
     * @return
     *     returns br.gov.camara.sitcamaraws.deputados.ObterLideresBancadasResponse.ObterLideresBancadasResult
     */
    @WebMethod(operationName = "ObterLideresBancadas", action = "http://www.camara.gov.br/SitCamaraWS/Deputados/ObterLideresBancadas")
    @WebResult(name = "ObterLideresBancadasResult", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/Deputados")
    @RequestWrapper(localName = "ObterLideresBancadas", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/Deputados", className = "br.gov.camara.sitcamaraws.deputados.ObterLideresBancadas")
    @ResponseWrapper(localName = "ObterLideresBancadasResponse", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/Deputados", className = "br.gov.camara.sitcamaraws.deputados.ObterLideresBancadasResponse")
    public br.gov.camara.sitcamaraws.deputados.ObterLideresBancadasResponse.ObterLideresBancadasResult obterLideresBancadas();

    /**
     * 
     * @return
     *     returns br.gov.camara.sitcamaraws.deputados.ObterIdCadastroOrcamentoResponse.ObterIdCadastroOrcamentoResult
     */
    @WebMethod(operationName = "ObterIdCadastroOrcamento", action = "http://www.camara.gov.br/SitCamaraWS/Deputados/ObterIdCadastroOrcamento")
    @WebResult(name = "ObterIdCadastroOrcamentoResult", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/Deputados")
    @RequestWrapper(localName = "ObterIdCadastroOrcamento", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/Deputados", className = "br.gov.camara.sitcamaraws.deputados.ObterIdCadastroOrcamento")
    @ResponseWrapper(localName = "ObterIdCadastroOrcamentoResponse", targetNamespace = "http://www.camara.gov.br/SitCamaraWS/Deputados", className = "br.gov.camara.sitcamaraws.deputados.ObterIdCadastroOrcamentoResponse")
    public br.gov.camara.sitcamaraws.deputados.ObterIdCadastroOrcamentoResponse.ObterIdCadastroOrcamentoResult obterIdCadastroOrcamento();

}
